name: Generate ASCII Artwork

on:
    push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo  
        uses: actions/checkout@v4
        
      - name: List Repo files
        run: ls -ltra

      - name: Update APT and Install Cowsay
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cowsay

      - name: Generate ASCII Dragon Art
        run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt  

    test_job:
      runs-on: ubuntu-latest
      needs: build_job
      steps:
        - name: download-text-file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: test dragon file exist
          run: grep -i "dragon" dragon.txt

    deploy_fob:
      runs-on: ubuntu-latest
      needs: test_job
      steps:
          - name: Download dragon text file
            uses: actions/download-artifact@v4
            with:
             name: dragon-text-file
             runs: dragon.txt
             
          - name: read from file
            run: cat dragon.txt
  

