name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo  
        uses: actions/checkout@v4
        
      - name: List Repo files
        run: ls -ltra

      - name: Update APT and Install Cowsay
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cowsay
          
      - name: Generate ASCII Dragon Art
        run: |
          cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt
          grep -i "dragon" dragon.txt
          cat dragon.txt
          ls -ltra

      - name: Executing Shell Script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
