name: Generate ASCII Artwork

on:
    push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo  
        uses: actions/checkout@v4
        
      - name: List Repo files
        run: ls -ltra

      - name: Update APT and Install Cowsay
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cowsay

      - name: Generate ASCII Dragon Art
        run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

    test_job:
      runs-on: ubuntu-latest
      needs: build_job
      steps:
        - name: test dragon file exist
          run: grep -i "dragon" dragon.txt

    deploy_fob:
      runs-on: ubuntu-latest
      needs: test_job
      steps:
          - name: read from file
            run: cat dragon.txt
  

